### ISSUE TITLE
Output images are all greyscale.

### ISSUE THREAD

**Issue by slayeryahu** [ykdai/BasicPBC#14]
Hello developers:

![image](https://github.com/ykdai/BasicPBC/assets/7860485/249176eb-7740-4279-b15a-46c34b8a04e9)
![image](https://github.com/ykdai/BasicPBC/assets/7860485/2a61370c-e571-4383-a1bc-73388c255173)

Version: Head version
![image](https://github.com/ykdai/BasicPBC/assets/7860485/365789f2-131c-495e-a4fc-68b23153a48c)

Device:  i5 13600kf,  Nvida 2080ti. Win 11.
No other error message reported.
[laughing_girl.zip](https://github.com/ykdai/BasicPBC/files/15008784/laughing_girl.zip)

Begging your reply.
Thank you.

**Comment by dienachtderwelt** [comment]
Hi thank you for your feedback.
It's caused by a lower version Scipy. Have switched to Numpy. Please pull the newest commit.
Hope you enjoy your exploring :)

**Comment by slayeryahu** [comment]
> Hi thank you for your feedback. It's caused by a lower version Scipy. Have switched to Numpy. Please pull the newest commit. Hope you enjoy your exploring :)

Fixed,thank you!
