### ISSUE TITLE
Can not pass a rolling ball test.

### ISSUE THREAD

**Issue by slayeryahu** [ykdai/BasicPBC#15]
3 issues found.
![image](https://github.com/ykdai/BasicPBC/assets/7860485/3a344b8c-f03f-4384-9775-e81f3d6e60b0)

1. high light marks turned into transparent.
2. high light region lost.
3. high light region recolored incorrect.

other: low graphic card usage and cpu usage when handling seg, when I input a complex original art. it takes very long time to prepare seg data with both gpu and cpu low usage. 
[ball(result).zip](https://github.com/ykdai/BasicPBC/files/15019409/ball.result.zip)
[ball(raw test).zip](https://github.com/ykdai/BasicPBC/files/15019411/ball.raw.test.zip)

**Comment by ykdai** [comment]
Hi, thank you for the feedback.
I have checked your test data and noticed that the position of ground truth `gt/0000.png`  and the line art `line/0000.png` do not match.

**Comment by ykdai** [comment]
Besides, if your lines are closed, you can ignore the `--seg_type trappedball`, the default segmentation preparation method is quite fast.

**Comment by slayeryahu** [comment]
> Besides, if your lines are closed, you can ignore the `--seg_type trappedball`, the default segmentation preparation method is quite fast.

Retested. 
A little better now.
Is there any limitation about the line?
the line mush pixel to pixel excatly to the gt frame?
the line must be hard edge line ( not soft blur) ? My painter always use soft line.
any limitation of line width? mush be 1 pix?
the hint line color must be 0xFF000 and 0x0000FF ?

**Comment by ykdai** [comment]
1. The line should be aligned with the gt frame pixel to pixel or only have a deviation with a few pixels. 
2. We have algorithm to post-process the soft line, so soft line is okay. However, if the color is too light, color leakage may also occur. This is the same as most of the paint bucket tools in non-vector based painting software.
3. There is no limitation about the line width.
4. In our current version, we just support hint line with color 0xFF0000, 0x00FF00 and 0x0000FF right now.

Besides, for large rotations, sometimes algorithms may find it difficult to determine the corresponding relationship. These areas will be marked as transparent for subsequent manual correction. At present, it is still an early version, and we will try our best to correct these problems in subsequent models. Thank you again for your question.
