### ISSUE TITLE
Recommended image resolution?

### ISSUE THREAD

**Issue by toyxyz** [ykdai/BasicPBC#2]
For the test sample, the resolution is 1024x1024, but can I use images with other resolutions?

I'm curious about the resolution of the available images. 

Thank you!

**Comment by ykdai** [comment]
Our current version only supports images with the resolution which can be divided by 16. We are going to release the code for inference with any resolution soon (in this week). Please stay tuned.

**Comment by ykdai** [comment]
We have already added inference code with any resolution and unclosed line arts. Feel free to test it now ! : )
