### ISSUE TITLE
加载后长时间等待

### ISSUE THREAD

**Issue by DamienCz** [ykdai/BasicPBC#21]
运行demo测试的时候一切正常很快就启动并且完成了，但是在进行自己的数据集测试（1920*1360 /28张图片）的时候当执行完seg之后就不动了等了很久也没有反应
![SGJ2K%}UH V4 PB(X`P5EQN](https://github.com/ykdai/BasicPBC/assets/132655237/a50f8b51-d105-495e-aa76-24a45d5e921e)

**Comment by DamienCz** [comment]
It's very random. Some sequences work and some don't.

**Comment by ykdai** [comment]
Hello, thank you for your feedback. We find that this problem occurs when your gt is not discrete, or lines are not drawn by binary pen. We have already fixed our processing pipeline to support these cases. You can pull the code to test it. Thank you.

**Comment by DamienCz** [comment]
> Hello, thank you for your feedback. We find that this problem occurs when your gt is not discrete, or lines are not drawn by binary pen. We have already fixed our processing pipeline to support these cases. You can pull the code to test it. Thank you.

Thank you for your reply and fixed this problem. I will test it again and give you feedback if there are other problems. By the way, if this project can go smoothly, it will greatly reduce the workload of the original artist. Thank you your contribution
