### ISSUE TITLE
Need help Please 🙏

### ISSUE THREAD

**Issue by Sarthak-999** [ykdai/BasicPBC#22]
I hope this message finds you well. As someone passionate about the 2D a animation,  I am reaching out to kindly ask for your guidance on a matter outside my expertise.
I am currently endeavoring to use this GitHub repository in Google Colab, but my coding knowledge is quite limited. If you could spare a moment to walk me through the process, step by step, I would be immensely grateful.
Thank you!!

**Comment by ykdai** [comment]
Hello, thank you for you advice. I am going to build a google colab repository to help you test our method by the end of this week. Please stay tuned.

**Comment by Sarthak-999** [comment]
Thank you !

**Comment by Sarthak-999** [comment]
Also does it work well with pixeleted colorization ?

**Comment by ykdai** [comment]
I have updated the Google Colab demo [here](https://colab.research.google.com/drive/1kJKLdFXY0O6jRxQCYS4xjaEcOTu7sLPu?usp=sharing). I am not sure what is your pixeleted line is like. If the line is enclosed, it should work. You can have a try first. If you meet any problems, be sure to contact us. We will solve these problems in our latest version and checkpoint.
