### ISSUE TITLE
Test set

### ISSUE THREAD

**Issue by evancasey** [ykdai/BasicPBC#23]
Author of AnT here :) thanks so much for this awesome work! Congratulations on the thoughtful improvements across every aspect of the problem.

I have a question about the hand-drawn test set. Is there any plan to release it? I'm interesting in benchmarking different approaches with BasicPBC. If the hand-drawn test set cannot be release for legal reasons, maybe we can work together and create a different hand-drawn test set that is OK to open source.

**Comment by ykdai** [comment]
Hi, Evan! We have been using the Cadmium all along and thank you for your wonderful insights in AnT. Our hand-drawn animation test set is mainly based on open-source hand-drawn anime project, so I am still not sure about the copyright problem. Thus, we just send it to other people through e-mail and are still confusing if it should be open-source or not.

Building a diverse hand-drawn open-source anime test set will be a very significant contribution for the community, and I am really glad to help. We can discuss the details using e-mail. My e-mail address is `ydai005@e.ntu.edu.sg`.

**Comment by evancasey** [comment]
Thanks! Will reach out via email
