### ISSUE TITLE
KeyError: "No object named 'PaintBucketLabelSegDataset' found in 'dataset' registry!"

### ISSUE THREAD

**Issue by riderexin** [ykdai/BasicPBC#25]
I run the following command.

"python basicsr/train.py -opt options/train/basicpbc_pbch_train_option.yml"

And an error occurred.

![image](https://github.com/ykdai/BasicPBC/assets/49785740/ae94bed2-88ee-49ad-9be7-9fcdce4df186)

I wonder how to find or register 'PaintBucketLabelSegDataset'.

**Comment by ykdai** [comment]
Thank you for your feedback. You could run `python setup.py develop` to solve this problem.

**Comment by riderexin** [comment]
> Thank you for your feedback. You could run `python setup.py develop` to solve this problem.

Thanks for the reply.
I had run the "python setup.py develop" already. 
After testing these days, I found it might be the problem of the torch version. I tried to use torch 2.3.1 before. And the code just asked me to install **basicsr** and needed a high version of torch-scatter which needs c++14.
When I turn to torch1.12.1+cu11.3, things seem to work.

**Comment by riderexin** [comment]
> Thank you for your feedback. You could run `python setup.py develop` to solve this problem.

By the way, in the paper, it is mentioned that "During the training stage, our model undergoes 300,000 iterations with a batch size of 2, utilizing NVIDIA GeForce RTX 3090 GPUs." would you mind sharing the details of your computing devices? 
I wonder the GPU RAM and the number of GPUs.

I'm currently running the code on a single 3080ti 12GB. I think the GPU RAM is not big enough to train with a batch size of more than 1.

**Comment by ykdai** [comment]
We are using NVIDIA GeForce RTX 3090 GPUs as stated in the paper with 24G memory.
![image](https://github.com/ykdai/BasicPBC/assets/111518177/e3d553db-b244-4c3d-8504-a0c80b677156)
