### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_scatte

### ISSUE THREAD

**Issue by HideyukiOgura** [ykdai/BasicPBC#27]
After executing `pip install -r requirements.txt` and `python setup.py develop`, I executed `python inference_line_frames.py --path dataset/test/laughing_girl` and `ModuleNotFoundError: No module named 'torch_scatter'` occurred.
Please let me know how to handle this.

**Comment by ykdai** [comment]
You may need to check your torch version at first, and then run `pip install torch-scatter` following this 'https://pypi.org/project/torch-scatter/'

**Comment by HideyukiOgura** [comment]
Thanks for the reply.
The error has been resolved.
