### ISSUE TITLE
RuntimeError: Caught RuntimeError in DataLoader worker process 0. &&  RuntimeError: Trying to resize storage that is not resizable

### ISSUE THREAD

**Issue by shawnl111** [ykdai/BasicPBC#3]
training on torch2.2.1 and cuda11.8 on widows11

**Comment by riderexin** [comment]
have the same problem.
if num_worker>0 and batch_size>1, I have the same error.
if num_worker = 0 and batch_size>1, stack error.

num_worker = 0 and batch_size=1,  it is ok

**Comment by riderexin** [comment]
The dataset itself has tensors of different shapes. So they can't be stacked anyway, in my opinion.
