### ISSUE TITLE
KeyError: "No object named 'PaintBucketSegMat' found in 'dataset' registry!"

### ISSUE THREAD

**Issue by bigfish144** [ykdai/BasicPBC#7]
Hello, when I tried to run Python Basicsr/test. py - opt options/test/basicpbc_pbch_test_option.yml, I encountered this error (I did not download the test set). KeyError: "No object named 'PaintBucketSegMat' found in 'dataset' registry!", and when I tested with my own data, I still encountered an error. What is the reason for this? Thank you very much for your answer

Name PaintBucketSegMat is not found, use name: PaintBucketSegMat_basicsr!
Traceback (most recent call last):
  File "/root/BasicPBC/basicsr/test.py", line 45, in <module>
    test_pipeline(root_path)
  File "/root/BasicPBC/basicsr/test.py", line 29, in test_pipeline
    test_set = build_dataset(dataset_opt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/shangse/lib/python3.11/site-packages/basicsr/data/__init__.py", line 34, in build_dataset
    dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/shangse/lib/python3.11/site-packages/basicsr/utils/registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'PaintBucketSegMat' found in 'dataset' registry!"

**Comment by ykdai** [comment]
It seems that you load the `basicsr` from the anaconda path, and not from the project path. Maybe you can solve this problem by running `python setup.py develop`.

**Comment by bigfish144** [comment]
你好，你发送的邮件我已经收到啦，我会尽快查看并处理的。祝好运。——丹妮

**Comment by bigfish144** [comment]
你好，你发送的邮件我已经收到啦，我会尽快查看并处理的。祝好运。——丹妮
